events { }

http {
    server {
        listen 443 ssl;
        server_name mtls.robson-cloud-devops.com;

        # Certificados do servidor
        ssl_certificate     /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        # Certificado da CA para validação de clientes
        ssl_client_certificate /etc/nginx/certs/ca.crt;
        ssl_verify_client on;  # mTLS obrigatório por padrão

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Health check do ALB - DESLIGA mTLS aqui
        location /health {
            ssl_verify_client off;        # Não exige certificado cliente
            return 200 'OK';
            add_header Content-Type text/plain;
        }

        # Todo o resto do tráfego exige mTLS
        location / {
            proxy_pass http://desafio-devops.desafio-devops.local:5000/api/webhook/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
}
