server {
    listen 443 ssl;
    server_name mtls.robson-cloud-devops.com;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384';

    ssl_client_certificate /etc/nginx/certs/ca.crt;
    ssl_verify_client on

    # Health check do ALB - sem mTLS
    location /health {
        proxy_pass http://desafio-devops.desafio-devops.local:5000/health;
    }


    # API/Webhook - exige certificado
    location /api {
        proxy_pass http://desafio-devops.desafio-devops.local:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Rotas internas padrão (opcional)
    location / {
        proxy_pass http://desafio-devops.desafio-devops.local:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
