name: Python CI

on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    branches: [ "main", "stage" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Rodar Pytest
        run: pytest -v || echo "Nenhum teste encontrado, apenas checagem semântica ok"
